#!/bin/bash
Release/Pedestrian\ Detection -classify Images/neg/00001147.png
Release/Pedestrian\ Detection -classify Images/neg/00001161.png
Release/Pedestrian\ Detection -classify Images/neg/00001162.png
Release/Pedestrian\ Detection -classify Images/neg/00001163.png
Release/Pedestrian\ Detection -classify Images/neg/00001165.png
Release/Pedestrian\ Detection -classify Images/neg/00001166.png
Release/Pedestrian\ Detection -classify Images/neg/00001167.png
Release/Pedestrian\ Detection -classify Images/neg/00001168.png
Release/Pedestrian\ Detection -classify Images/neg/00001169.png
Release/Pedestrian\ Detection -classify Images/neg/00001170.png
Release/Pedestrian\ Detection -classify test4.png
Release/Pedestrian\ Detection -classify test3.png
Release/Pedestrian\ Detection -classify test2.png
Release/Pedestrian\ Detection -classify test.png
Release/Pedestrian\ Detection -classify Images/pos/person_and_bike_163a.png
Release/Pedestrian\ Detection -classify Images/pos/person_and_bike_163b.png
Release/Pedestrian\ Detection -classify Images/pos/person_350a.png
Release/Pedestrian\ Detection -classify Images/pos/person_350b.png
Release/Pedestrian\ Detection -classify Images/pos/person_350c.png
Release/Pedestrian\ Detection -classify Images/pos/person_350d.png
Release/Pedestrian\ Detection -classify Images/pos/person_350e.png
Release/Pedestrian\ Detection -classify Images/pos/person_350f.png
Release/Pedestrian\ Detection -classify Images/pos/person_350g.png
Release/Pedestrian\ Detection -classify Images/pos/person_350h.png
Release/Pedestrian\ Detection -classify Images/pos/person_335a.png
Release/Pedestrian\ Detection -classify Images/pos/person_335b.png
